name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '15'

      - run: npm ci
      - run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '15'

      - run: npm ci
      - run: npm run test:ci
      - run: npx codecov

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '15'

      - run: npm ci
      - run: npm run standard

  docker-buildx:
    needs: [ build, test, lint ]
    name: Docker Buildx
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build platforms
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/defich/whale:latest

  docker-sanity:
    needs: [ build, test, lint ]
    name: Docker Sanity Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup docker containers
        run: docker-compose -f __sanity__/docker-compose.yml up -d

      - name: Wait for
        run: ./__sanity__/wait-for http://localhost:3000/_health/probes/liveness -t 6

      - name: Sanity testing
        uses: matt-ball/newman-action@0659e9b8d056c0d03d94e1dbfce380512088b566
        with:
          collection: __sanity__/postman_collection.json

  packages-build:
    name: Packages Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '15'

      - run: npm ci
      - run: npm run packages:build
