name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
        with:
          node-version: '15'
          cache: 'npm'

      - run: npm ci
      - run: npm run build

  packages-build:
    name: Packages Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
        with:
          node-version: '15'
          cache: 'npm'

      - run: npm ci
      - run: npm run packages:build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
        with:
          node-version: '15'
          cache: 'npm'

      - run: npm ci
      - run: npm run test:ci
      - uses: codecov/codecov-action@51d810878be5422784e86451c0e7c14e5860ec47
        with:
          fail_ci_if_error: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
        with:
          node-version: '15'
          cache: 'npm'

      - run: npm ci
      - run: npx --no-install ts-standard

  docker-buildx:
    needs: [ build, lint ]
    name: Docker Buildx
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0

      - name: Build platforms
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          push: false
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/defich/whale:latest

  docker-sanity:
    needs: [ build, lint ]
    name: Docker Sanity Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Setup docker containers
        run: docker-compose -f .github/workflows/ci/docker-compose.yml up -d

      - name: Wait for
        run: .github/workflows/ci/wait-for http://localhost:3000/_actuator/probes/liveness -t 6

      - name: Sanity testing
        uses: matt-ball/newman-action@0659e9b8d056c0d03d94e1dbfce380512088b566
        with:
          collection: .github/workflows/ci/postman_collection.json
