name: DeFiChain Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  jellyfish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: 16

      - run: npx npm-check-updates -l m -u --deep --target newest --pre -f "/^defichain|@defichain\/.+/" -x "/^@defichain\/(whale|playground)-.+/"

      - name: Upgrade dependencies
        run: |
          if ! git diff-index --quiet HEAD; then
            npm i
          else
            echo "no file has been changed"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@bd72e1b7922d417764d27d30768117ad7da78a0e
        with:
          labels: kind/dependencies
          committer: DeFiChain Bot <github-bot@defichain.com>
          author: DeFiChain Bot <github-bot@defichain.com>
          title: "bump(deps): @defichain/* dependencies"
          commit-message: Bump @defichain/jellyfish dependencies
          body: |
            #### What kind of PR is this?:
            /kind dependencies
            #### What this PR does / why we need it:
            Bump `@defichain/jellyfish` dependencies to the latest release.
          branch: defichain-bot/bump-jellyfish-deps
