name: NestJS Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: 16

      - name: Upgrade dependencies
        run: |
          npx npm-check-updates -l m -u -f "/^@nestjs\/.+/" \
          | grep -q 'Run npm install to install new versions' && \
          npm i

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@bd72e1b7922d417764d27d30768117ad7da78a0e
        with:
          token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          labels: kind/dependencies
          commit-message: Bump @nestjs dependencies
          committer: DeFiChain Bot <github-bot@defichain.com>
          author: DeFiChain Bot <github-bot@defichain.com>
          title: Bump @nestjs dependencies
          body: |
            #### What kind of PR is this?:
            /kind dependencies
            #### What this PR does / why we need it:
            Bump `@nestjs/*` dependencies to the newest release.
          branch: defichain-bot/bump-nestjs-deps
