name: Publish

on:
  release:
    types: [ published, prereleased ]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    environment: Docker Release
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@aa759c6c94d3800c55b8601f21ba4b2371704cb7
        with:
          node-version: '15'

      - uses: actions/github-script@a3e7071a34d7e1f219a8a4de9a5e0a34d1ee1293
        id: version
        with:
          script: |
            const semver = context.ref.replace('refs/tags/v', '')
            if (semver.match(/[0-9]\.[0-9]\.[0-9]/)) {
              return semver
            }

            throw new Error('not semver')
          result-encoding: string

      - run: npm ci
      - run: npm run publish:version ${{ steps.version.outputs.result }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935
        with:
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ghcr.io/defich/whale:latest
            ghcr.io/defich/whale:${{ steps.version.outputs.result }}


  npm:
    name: NPM
    runs-on: ubuntu-latest
    environment: NPM Release
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@aa759c6c94d3800c55b8601f21ba4b2371704cb7
        with:
          node-version: '15'

      - uses: actions/github-script@a3e7071a34d7e1f219a8a4de9a5e0a34d1ee1293
        id: version
        with:
          script: |
            const semver = context.ref.replace('refs/tags/v', '')
            if (semver.match(/[0-9]\.[0-9]\.[0-9]/)) {
              return semver
            }

            throw new Error('not semver')
          result-encoding: string

      - run: npm ci
      - run: npm run publish:version ${{ steps.version.outputs.result }}
      - run: npm run packages:build

      - name: Publish Next
        if: github.event.release.prerelease
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm run packages:publish:next
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish Latest
        if: "!github.event.release.prerelease"
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm run packages:publish:latest
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

